name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
        cache-dependency-path: ''
    
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt

    - name: Cache judge data
      uses: actions/cache@v4
      with:
        path: |
          .verify-helper/cache/
          ~/.cache/online-judge-tools/library-checker-problems/
          ~/.local/share/online-judge-tools/
        key: cache-judge-data

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all

    - run: git switch main
